# Generated by Django 4.2.6 on 2023-10-31 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga_shops', '0002_manga_shops_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('rate_stars', models.CharField(choices=[('*', '*'), ('* *', '* *'), ('* * *', '* * *'), ('* * * *', '* * * *'), ('* * * * *', '* * * * *')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga_select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_object', to='manga_shops.manga_shops')),
            ],
        ),
    ]
